fix

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -320,17 +320,15 @@ runs:
       mkdir -p _validation-images/benchmarks
 
       # Copy benchmark plots
-      for plotpath in "${plots_array_benchmark[@]}"
+      for plot in "${plots_array_benchmark[@]}"
       do
-        subpath="${plotpath%/*}"
-        plot="${plotpath##*/}"
-        echo "Copying benchmark plot: ${plot} from path: ${subpath}"
+        echo "Copying benchmark plot: ${plot}
 
         # Create directories
-        mkdir -p "_validation-images/benchmarks/${subpath}"
+        mkdir -p "_validation-images/benchmarks
 
-        cp "$HOME/${subpath}/${plot}" "_validation-images/benchmarks/${subpath}/" || true # ignore if run failed
-        cp "$HOME/${subpath}/${plot}" "_validation-images/benchmarks/${subpath}/" || true # ignore if run failed
+        cp "$HOME/${plot}" "_validation-images/benchmarks" || true # ignore if run failed
+        cp "$HOME/${plot}" "_validation-images/benchmarks" || true # ignore if run failed
       done
 
       # Add plots to repo branch
