more stuff

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -7,8 +7,8 @@ inputs:
     required: true
     type: choice
     options:
-      - 'run-self-hosted-validation'
-      - 'create-comment'
+    - 'run-self-hosted-validation'
+    - 'create-comment'
   # Needed for 'run-self-hosted-validation' step
   env_file:
     description: 'File for conda/mamba environment'
@@ -28,7 +28,7 @@ inputs:
   repo_private_key:
     description: 'Private key to access the plots repo'
     type: string
-  
+
   dev:
     description: 'Run in development mode'
     type: boolean
@@ -40,248 +40,238 @@ inputs:
 
 runs:
   using: "composite"
+  env:
+    REPO: ${{ github.repository }}
+    BRANCH_NAME_MAIN: ${{ github.base_ref }}
+    BRANCH_NAME_FEATURE: ${{ github.head_ref }}
   steps:
 
     # ----------------------------------------
     # 'run-self-hosted-validation' step
     # ----------------------------------------
-    - name: Run self-hosted validation
-      if: ${{ inputs.step == 'run-self-hosted-validation' }}
+  - name: Run self-hosted validation
+    if: ${{ inputs.step == 'run-self-hosted-validation' }}
+    run: |
+      echo "Running self-hosted validation..."
 
-      
-      run: |
-        echo "Running self-hosted validation..."
-        
-        # Check for dev mode
-        USERNAME=$(whoami)
-        if [ "${{ inputs.dev }}" = true ]; then
-            echo "Development mode activated."
-            command_prefix="/home/$USERNAME/runner-scripts/run-dev.sh"
-        else
-            command_prefix="/home/$USERNAME/runner-scripts/run.sh"
-        fi
+      # Check for dev mode
+      USERNAME=$(whoami)
+      if [ "${{ inputs.dev }}" = true ]; then
+          echo "Development mode activated."
+          command_prefix="/home/$USERNAME/runner-scripts/run-dev.sh"
+      else
+          command_prefix="/home/$USERNAME/runner-scripts/run.sh"
+      fi
 
-        # Fetch the hashes (without checking out the code)
-        _HASH_MAIN=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
-        "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.base_ref }}" | jq -r '.sha')
-        _HASH_FEATURE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
-        "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.head_ref }}" | jq -r '.sha')
-        echo "Main branch (${{ github.base_ref }}) hash: $_HASH_MAIN"
-        echo "Feature branch (${{ github.head_ref }}) hash: $_HASH_FEATURE"
-        
-        echo "${{ github.event.pull_request.head.repo.full_name }}"
+      # Fetch the hashes (without checking out the code)
+      _hash_main=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+      "https://api.github.com/repos/$REPO/commits/$BRANCH_NAME_MAIN" | jq -r '.sha')
+      _hash_feature=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+      "https://api.github.com/repos/$REPO/commits/$BRANCH_NAME_FEATURE" | jq -r '.sha')
+      echo "Main branch ($BRANCH_NAME_MAIN) hash: $_hash_main"
+      echo "Feature branch ($BRANCH_NAME_FEATURE) hash: $_hash_feature"
 
-        # Execute the command with the common arguments
-        $command_prefix \
-        --repo ${{ github.repository }} \
-        --branch_main ${{ github.base_ref }} \
-        --branch_feature "pr/${{ github.event.number }}" \
-        --hash_main $_HASH_MAIN \
-        --hash_feature $_HASH_FEATURE \
-        --env_file ${{ inputs.env_file }} \
-        --config_file ${{ inputs.snakemake_config }} \
-        --pre_command "${{ inputs.pre_command }}" \
-        --main_command "ariadne_all"
-      shell: bash
+      echo "${{ github.event.pull_request.head.repo.full_name }}"
+
+      # Execute the command with the common arguments
+      $command_prefix \
+      --repo $REPO \
+      --branch_main $BRANCH_NAME_MAIN \
+      --branch_feature "pr/${{ github.event.number }}" \
+      --hash_main $_hash_main \
+      --hash_feature $_hash_feature \
+      --env_file ${{ inputs.env_file }} \
+      --config_file ${{ inputs.snakemake_config }} \
+      --pre_command "${{ inputs.pre_command }}" \
+      --main_command "ariadne_all"
+    shell: bash
 
     # ----------------------------------------
     # 'create-comment' step
     # ----------------------------------------
-    - name: Download artifacts
-      if: ${{ inputs.step == 'create-comment' }}
-      uses: actions/download-artifact@v4
-    
-    - name: Move artifacts to home directory
-      if: ${{ inputs.step == 'create-comment' }}
-      run: |
-        # Move artifacts to home directory
-        mkdir $HOME/artifacts
-        mv ./* $HOME/artifacts
-      shell: bash
-  
-    - name: Get variables from artifacts
-      if: ${{ inputs.step == 'create-comment' }}
-      id: env-variables-artifacts
-      run: |
-        # Get compared hashes
-        hash_main=$(yq e '.parameters.hash_main' $HOME/artifacts/logs/validator-metadata.yml)
-        hash_feature=$(yq e '.parameters.hash_feature' $HOME/artifacts/logs/validator-metadata.yml)
+  - name: Download artifacts
+    if: ${{ inputs.step == 'create-comment' }}
+    uses: actions/download-artifact@v4
 
-        # Assert variables found  
-        if [[ -z $hash_main || -z $hash_feature ]]; then
-          echo "Error: Commit hashes not found"
-          exit 1
-        fi
+  - name: Move artifacts to home directory
+    if: ${{ inputs.step == 'create-comment' }}
+    run: |
+      # Move artifacts to home directory
+      mkdir $HOME/artifacts
+      mv ./* $HOME/artifacts
+    shell: bash
 
-        # Print and save variables
-        echo "Main commit hash: ${hash_main}"
-        echo "Feature commit hash: ${hash_feature}"
-        echo "hash_main=${hash_main}" >> $GITHUB_OUTPUT
-        echo "hash_feature=${hash_feature}" >> $GITHUB_OUTPUT
+  - name: Get variables from artifacts
+    if: ${{ inputs.step == 'create-comment' }}
+    run: |
+      # Get compared hashes
+      echo "HASH_MAIN=$(yq e '.parameters.hash_main' $HOME/artifacts/logs/validator-metadata.yml)" >> $GITHUB_ENV
+      echo "HASH_FEATURE=$(yq e '.parameters.hash_feature' $HOME/artifacts/logs/validator-metadata.yml)" >> $GITHUB_ENV
+      echo "Main commit hash: ${HASH_MAIN}"
+      echo "Feature commit hash: ${HASH_FEATURE}"
 
-        # Get config prefix
-        prefix_main=$(yq e '.metadata.prefix_main' $HOME/artifacts/logs/validator-metadata.yml)
-        prefix_feature=$(yq e '.metadata.prefix_feature' $HOME/artifacts/logs/validator-metadata.yml)
-        
-        # Assert variables found
-        if [[ -z $prefix_main || -z $prefix_feature ]]; then
-          echo "Error: Config prefixes not found"
-          exit 1
-        fi
+      # Assert variables found  
+      if [[ -z $HASH_MAIN || -z $HASH_FEATURE ]]; then
+        echo "Error: Commit hashes not found"
+        exit 1
+      fi
 
-        # Print and save variables
-        echo "Main config prefix: ${prefix_main}"
-        echo "Feature config prefix: ${prefix_feature}"
-        echo "prefix_main=${prefix_main}" >> $GITHUB_OUTPUT
-        echo "prefix_feature=${prefix_feature}" >> $GITHUB_OUTPUT
+      # Get config prefix
+      echo "PREFIX_MAIN=$(yq e '.metadata.prefix_main' $HOME/artifacts/logs/validator-metadata.yml)" >> $GITHUB_ENV
+      echo "PREFIX_FEATURE=$(yq e '.metadata.prefix_feature' $HOME/artifacts/logs/validator-metadata.yml)" >> $GITHUB_ENV
+      echo "Main config prefix: ${PREFIX_MAIN}"
+      echo "Feature config prefix: ${PREFIX_FEATURE}"
 
-      shell: bash
+      # Assert variables found
+      if [[ -z $PREFIX_MAIN || -z $PREFIX_FEATURE ]]; then
+        echo "Error: Config prefixes not found"
+        exit 1
+      fi
 
-    - name: Checkout main repo
-      if: ${{ inputs.step == 'create-comment' }}
-      uses: actions/checkout@v4
-      with:
-        fetch-depth: 0
+    shell: bash
 
-    - name: Get variables from repo
-      if: ${{ inputs.step == 'create-comment' }}
-      id: env-variables-repo
-      run: |
-        # Get git diff of used snakemake config
-        git_diff_config=$(git diff ${{ steps.env-variables-artifacts.outputs.hash_main }} ${{ steps.env-variables-artifacts.outputs.hash_feature }} -- ${{ inputs.snakemake_config }})
-        # echo "GIT_DIFF_CONFIG='${git_diff_config}'" >> $GITHUB_ENV
-        echo "GIT_DIFF_CONFIG<<EOF" >> $GITHUB_ENV
-        echo "${git_diff_config}" >> $GITHUB_ENV
-        echo "EOF" >> $GITHUB_ENV
-        echo "git_diff_config:\n${git_diff_config}"
+  - name: Checkout main repo
+    if: ${{ inputs.step == 'create-comment' }}
+    uses: actions/checkout@v4
+    with:
+      fetch-depth: 0
 
-        # Get the number of commits ahead of main
-        behind_count=$(git rev-list --right-only --count ${{ steps.env-variables-artifacts.outputs.hash_feature }}...${{ steps.env-variables-artifacts.outputs.hash_main }})
-        ahead_count=$(git rev-list --left-only --count ${{ steps.env-variables-artifacts.outputs.hash_feature }}...${{ steps.env-variables-artifacts.outputs.hash_main }})
-        echo "BEHIND_COUNT=${behind_count}" >> $GITHUB_ENV
-        echo "behind_count: ${behind_count}"
-        echo "AHEAD_COUNT=${ahead_count}" >> $GITHUB_ENV
-        echo "ahead_count: ${ahead_count}"
-      shell: bash
+  - name: Get variables from repo
+    if: ${{ inputs.step == 'create-comment' }}
+    id: env-variables-repo
+    run: |
+      # Get git diff of used snakemake config
+      git_diff_config=$(git diff $HASH_MAIN $HASH_FEATURE -- ${{ inputs.snakemake_config }})
+      # Write to env
+      echo "GIT_DIFF_CONFIG<<EOF" >> $GITHUB_ENV
+      echo "${git_diff_config}" >> $GITHUB_ENV
+      echo "EOF" >> $GITHUB_ENV
+      echo "Git diff config:\n${git_diff_config}"
 
-    - name: Checkout plot repo
-      if: ${{ inputs.step == 'create-comment' }}
-      uses: actions/checkout@v4
-      with:
-        repository: lkstrp/pypsa-validator
-        ref: ${{ github.repository }}
-        ssh-key: ${{ inputs.repo_private_key }}
+      # Get the number of commits ahead of main
+      echo "BEHIND_COUNT=$(git rev-list --right-only --count $HASH_FEATURE...$HASH_MAIN)" >> $GITHUB_ENV
+      echo "AHEAD_COUNT=$(git rev-list --left-only --count $HASH_FEATURE...$HASH_MAIN)" >> $GITHUB_ENV
+      echo "Behind count: $BEHIND_COUNT"
+      echo "Ahead count: $AHEAD_COUNT"
 
-    - name: Upload relevant plots
-      id: upload-plots
-      if: ${{ inputs.step == 'create-comment' }}
-      run: |
-        rm -rf _validation-images
-        mkdir -p _validation-images/feature
-        mkdir -p _validation-images/main
-                
-        # Copy plots  
-        read -a plots_array <<< ${{ inputs.plots }}
-        echo "Plots: ${plots_array[@]}"
-        for plot in "${plots_array[@]}"
-        do
-          echo "Copying ${plot}"
-          cp -r "$HOME/artifacts/results (main branch)/${{ steps.env-variables-artifacts.outputs.prefix_main }}/${plot}" "_validation-images/main" || true # ignore if run failed
-          cp -r "$HOME/artifacts/results (feature branch)/${{ steps.env-variables-artifacts.outputs.prefix_feature }}/${plot}" "_validation-images/feature" || true # ignore if run failed
-        done
+    shell: bash
 
-        # Bot config
-        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
-        git config --global user.name "github-actions[bot]"
+  - name: Checkout plot repo
+    if: ${{ inputs.step == 'create-comment' }}
+    uses: actions/checkout@v4
+    with:
+      repository: lkstrp/pypsa-validator
+      ref: $REPO
+      ssh-key: ${{ inputs.repo_private_key }}
 
-        # Add plots to repo branch
-        echo "Adding plots to repo branch"
-        git add _validation-images
-        git commit -m "[github-actions.ci] upload validation images to show in comment" || true # ignore if no changes
-        git push origin ${{ github.repository }}
-        echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
-      shell: bash
+  - name: Upload relevant plots
+    id: upload-plots
+    if: ${{ inputs.step == 'create-comment' }}
+    run: |
+      rm -rf _validation-images
+      mkdir -p _validation-images/feature
+      mkdir -p _validation-images/main
+              
+      # Copy plots  
+      read -a plots_array <<< ${{ inputs.plots }}
+      echo "Plots: ${plots_array[@]}"
+      for plot in "${plots_array[@]}"
+      do
+        echo "Copying ${plot}"
+        cp -r "$HOME/artifacts/results (main branch)/${PREFIX_MAIN}/${plot}" "_validation-images/main" || true # ignore if run failed
+        cp -r "$HOME/artifacts/results (feature branch)/${PREFIX_FEATURE}/${plot}" "_validation-images/feature" || true # ignore if run failed
+      done
 
-    - name: Draft comment
-      if: ${{ inputs.step == 'create-comment' }}
-      run: |
-        # Get potential changes from main branch
-        git fetch origin
-        git merge origin/main --allow-unrelated-histories
+      # Bot config
+      git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+      git config --global user.name "github-actions[bot]"
 
-        echo "${{ inputs.plots }}"
-        pip install -r requirements.txt
-        python draft_comment.py \
-        --repo ${{ github.repository }} \
-        --artifact_url "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
-        --branch_name_main ${{ github.base_ref }} \
-        --branch_name_feature ${{ github.head_ref }} \
-        --hash_main "${{ steps.env-variables-artifacts.outputs.hash_main }}" \
-        --hash_feature "${{ steps.env-variables-artifacts.outputs.hash_feature }}" \
-        --config_prefix "${{ steps.env-variables-repo.outputs.config_prefix }}" \
-        --dir_base "$HOME/artifacts/results (main branch)" \
-        --dir_feature "$HOME/artifacts/results (feature branch)" \
-        --plots_hash ${{ steps.upload-plots.outputs.COMMIT_ID }} \
-        --plots "${{ inputs.plots }}" \
-        > comment.txt
-      shell: bash
+      # Add plots to repo branch
+      echo "Adding plots to repo branch"
+      git add _validation-images
+      git commit -m "[github-actions.ci] upload validation images to show in comment" || true # ignore if no changes
+      git push origin $REPO
+      echo "COMMIT_ID=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
+    shell: bash
 
-    - name: Retrieve or create comment
-      if: ${{ inputs.step == 'create-comment' }}
-      id: comment
-      uses: actions/github-script@v7
-      with:
-        script: |
-          const owner = context.repo.owner;
-          const repo = context.repo.repo;
-          const issue_number = context.issue.number;
-          
-          // Fetching all comments of pr
-          const comments = await github.rest.issues.listComments({
+  - name: Draft comment
+    if: ${{ inputs.step == 'create-comment' }}
+    run: |
+      # Get potential changes from main branch
+      git fetch origin
+      git merge origin/main --allow-unrelated-histories
+
+      # Install requirements
+      pip install -r requirements.txt
+
+      # Set env variables needed for script
+      echo "ARTIFACT_URL="https://github.com/$REPO/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV
+      echo "DIR_MAIN=$HOME/artifacts/results (main branch)" >> $GITHUB_ENV
+      echo "DIR_FEATURE=$HOME/artifacts/results (feature branch)" >> $GITHUB_ENV
+      echo "DIR_LOGS=$HOME/artifacts/logs" >> $GITHUB_ENV
+      echo "PLOTS_HASH=${{ steps.upload-plots.outputs.COMMIT_ID }}" >> $GITHUB_ENV
+      echo "PLOTS=${{ inputs.plots }}" >> $GITHUB_ENV
+
+      # Draft comment
+      python draft_comment.py > comment.txt
+    shell: bash
+
+  - name: Retrieve or create comment
+    if: ${{ inputs.step == 'create-comment' }}
+    id: comment
+    uses: actions/github-script@v7
+    with:
+      script: |
+        const owner = context.repo.owner;
+        const repo = context.repo.repo;
+        const issue_number = context.issue.number;
+
+        // Fetching all comments of pr
+        const comments = await github.rest.issues.listComments({
+          owner,
+          repo,
+          issue_number
+        });
+
+          // Distinctive keyword present in bot's comments 
+        const distinctiveKeyword = '_val-bot-id-keyword_';
+
+        // Searching for existing comment with the distinctive keyword
+        let botsComment;
+        for (let { user, id, body } of comments.data.reverse()) {
+          if (body.includes(distinctiveKeyword)) {
+            botsComment = { id, body };
+            break;
+          }
+        }
+
+        // If found return its id
+        if (botsComment) {
+          return botsComment.id; 
+        } else {
+          // Creating a new comment if it doesn't exist yet and returning its ID.
+          const { data: newComment } = await github.rest.issues.createComment({
             owner,
             repo,
-            issue_number
+            issue_number,
+            body: `<!-- ${distinctiveKeyword} --> Initializing comment...`
           });
-
-            // Distinctive keyword present in bot's comments 
-          const distinctiveKeyword = '_val-bot-id-keyword_';
-
-          // Searching for existing comment with the distinctive keyword
-          let botsComment;
-          for (let { user, id, body } of comments.data.reverse()) {
-            if (body.includes(distinctiveKeyword)) {
-              botsComment = { id, body };
-              break;
-            }
-          }
           
-          // If found return its id
-          if (botsComment) {
-            return botsComment.id; 
-          } else {
-            // Creating a new comment if it doesn't exist yet and returning its ID.
-            const { data: newComment } = await github.rest.issues.createComment({
-              owner,
-              repo,
-              issue_number,
-              body: `<!-- ${distinctiveKeyword} --> Initializing comment...`
-            });
-            
-            return newComment.id;
-          }
+          return newComment.id;
+        }
 
-    - name: Update comment
-      if: ${{ inputs.step == 'create-comment' }}
-      uses: actions/github-script@v7
-      with:
-        script: |
-          const fs = require('fs');
-          let comment = fs.readFileSync('comment.txt', 'utf8');
-      
-          github.rest.issues.updateComment({
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            comment_id: ${{ steps.comment.outputs.result }},
-            body: comment
-          });
+  - name: Update comment
+    if: ${{ inputs.step == 'create-comment' }}
+    uses: actions/github-script@v7
+    with:
+      script: |
+        const fs = require('fs');
+        let comment = fs.readFileSync('comment.txt', 'utf8');
+
+        github.rest.issues.updateComment({
+          owner: context.repo.owner,
+          repo: context.repo.repo,
+          comment_id: ${{ steps.comment.outputs.result }},
+          body: comment
+        });
 
