feat: add variable comparison plots

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -201,24 +201,57 @@ runs:
       ssh-key: ${{ inputs.validator_key }}
       path: validator-repo
 
+  - name: Setup environment and retrieve scripts
+    if: ${{ inputs.step == 'create-comment' }}
+    run: |
+      cd $GITHUB_WORKSPACE/validator-repo
+
+      # Get potential changes from main branch
+      git fetch origin
+      if [ "${{ inputs.dev }}" = true ]; then
+          echo "Merging from dev instead of main."
+          git merge origin/dev --allow-unrelated-histories -X theirs
+      else
+          git merge origin/main --allow-unrelated-histories -X theirs
+      fi
+
+      # Install requirements
+      pip install -r requirements.txt
+
+    shell: bash
+
   - name: Upload relevant plots
     id: upload-plots
     if: ${{ inputs.step == 'create-comment' }}
     run: |
       cd $GITHUB_WORKSPACE/validator-repo
 
+      # Get static plot list (from input)
+      read -a plots_array_input <<< ${{ inputs.plots }}
+      # Get dynamic plot list (from comment script)
+      read -a plots_array_dynamic <<< "$(python draft_comment.py plots)"
+
+      plots_array=("${plots_array_input[@]}" "${plots_array_dynamic[@]}")
+
+      # Empty directory
       rm -rf _validation-images
       mkdir -p _validation-images/feature
       mkdir -p _validation-images/main
               
       # Copy plots  
-      read -a plots_array <<< ${{ inputs.plots }}
       echo "Plots: ${plots_array[@]}"
-      for plot in "${plots_array[@]}"
+      for plotpath in "${plots_array[@]}"
       do
-        echo "Copying ${plot}"
-        cp -r "$HOME/artifacts/results (main branch)/${PREFIX_MAIN}/${plot}" "_validation-images/main" || true # ignore if run failed
-        cp -r "$HOME/artifacts/results (feature branch)/${PREFIX_FEATURE}/${plot}" "_validation-images/feature" || true # ignore if run failed
+        subpath="${plotpath%/*}"
+        plot="${plotpath##*/}"
+        echo "Copying plot: ${plot} from path: ${subpath}"
+
+        # Create directories
+        mkdir -p "_validation-images/main/${subpath}"
+        mkdir -p "_validation-images/feature/${subpath}"
+
+        cp "$HOME/artifacts/results (main branch)/${PREFIX_MAIN}/${subpath}/${plot}" "_validation-images/main/${subpath}/" || true # ignore if run failed
+        cp "$HOME/artifacts/results (feature branch)/${PREFIX_FEATURE}/${subpath}/${plot}" "_validation-images/feature/${subpath}/" || true # ignore if run failed
       done
 
       # Add plots to repo branch
@@ -230,7 +263,7 @@ runs:
 
     shell: bash
 
-  - name: Set env for comment script
+  - name: Setup env variables for comment
     if: ${{ inputs.step == 'create-comment' }}
     run: |
       # This needs to be done in a separate step to ensure the output is available
@@ -243,26 +276,6 @@ runs:
     if: ${{ inputs.step == 'create-comment' }}
     run: |
       cd $GITHUB_WORKSPACE/validator-repo
-
-      # Get potential changes from main branch
-      git fetch origin
-      if [ "${{ inputs.dev }}" = true ]; then
-          echo "Merging from dev instead of main."
-          git merge origin/dev --allow-unrelated-histories
-      else
-          git merge origin/main --allow-unrelated-histories
-      fi
-
-      # Install requirements
-      pip install -r requirements.txt
-
-      # # Set env for multiline plots string
-      # read -a plots_array <<< ${{ inputs.plots }}
-      # IFS=' '
-      # plots_string="${plots_array[*]}"
-      # echo "${plots_string}"
-      # echo "PLOTS=\"${plots_string}\"" >> $GITHUB_ENV 
-      # unset IFS
 
       # Draft comment
       # Note: The script uses many env variables. See the script for more details.
